spring.application.name=WebCSAT

server.port=8081

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://mycbtdb.cx64mma2muvn.ap-southeast-2.rds.amazonaws.com:3306/cbtdb
spring.datasource.username=root
spring.datasource.password=q1w2e3r42025!!

spring.jpa.show-sql=true