spring.application.name=WebCSAT
server.port=8080

# Set MariaDB by AWS
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://mycbtdb.cx64mma2muvn.ap-southeast-2.rds.amazonaws.com:3306/cbtdb?characterEncoding=utf8mb4&useUnicode=true
spring.datasource.username=root
spring.datasource.password=q1w2e3r42025!!

# Set JPA
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

# JWT issuer and SecretKey
jwt.issuer=cbtsuneung@gmail.com
jwt.secret_key=q1w2e3r4!!@@q1w2e3r4!!@@

# Set Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cbtsuneung@gmail.com
spring.mail.password=gnpouctdovpoghuq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true